import { MediaPost } from './types'

export const mockPostsData: MediaPost[] = [
  {
    ig_media_id: '001',
    ig_user_id: 'mock_account_1',
    timestamp: '2025-08-29T10:00:00Z',
    media_type: 'CAROUSEL_ALBUM',
    caption: 'Beautiful sunset at the beach #photography #sunset',
    media_url: 'https://picsum.photos/800/800?random=1',
    thumbnail_url: 'https://picsum.photos/400/400?random=1',
    permalink: 'https://www.instagram.com/p/mock001/',
    like_count: 1,
    comments_count: 0,
    reach: 35,
    views: 97,
    shares: 0,
    saved: 0
  },
  {
    ig_media_id: '002',
    ig_user_id: 'mock_account_1',
    timestamp: '2025-08-28T14:30:00Z',
    media_type: 'CAROUSEL_ALBUM',
    caption: 'Delicious homemade pasta recipe #food #cooking',
    media_url: 'https://picsum.photos/800/800?random=2',
    thumbnail_url: 'https://picsum.photos/400/400?random=2',
    permalink: 'https://www.instagram.com/p/mock002/',
    like_count: 3,
    comments_count: 0,
    reach: 46,
    views: 122,
    shares: 0,
    saved: 0
  },
  {
    ig_media_id: '003',
    ig_user_id: 'mock_account_1',
    timestamp: '2025-08-26T16:45:00Z',
    media_type: 'CAROUSEL_ALBUM',
    caption: 'Weekend coffee time ☕ #coffee #lifestyle',
    media_url: 'https://picsum.photos/800/800?random=3',
    thumbnail_url: 'https://picsum.photos/400/400?random=3',
    permalink: 'https://www.instagram.com/p/mock003/',
    like_count: 6,
    comments_count: 0,
    reach: 46,
    views: 106,
    shares: 0,
    saved: 0
  },
  {
    ig_media_id: '004',
    ig_user_id: 'mock_account_1',
    timestamp: '2025-08-22T11:20:00Z',
    media_type: 'CAROUSEL_ALBUM',
    caption: 'Nature walk in the forest 🌲 #nature #hiking',
    media_url: 'https://picsum.photos/800/800?random=4',
    thumbnail_url: 'https://picsum.photos/400/400?random=4',
    permalink: 'https://www.instagram.com/p/mock004/',
    like_count: 4,
    comments_count: 0,
    reach: 45,
    views: 81,
    shares: 0,
    saved: 0
  },
  {
    ig_media_id: '005',
    ig_user_id: 'mock_account_1',
    timestamp: '2025-08-21T09:15:00Z',
    media_type: 'CAROUSEL_ALBUM',
    caption: 'City lights at night ✨ #city #night #photography',
    media_url: 'https://picsum.photos/800/800?random=5',
    thumbnail_url: 'https://picsum.photos/400/400?random=5',
    permalink: 'https://www.instagram.com/p/mock005/',
    like_count: 6,
    comments_count: 0,
    reach: 40,
    views: 86,
    shares: 0,
    saved: 0
  },
  {
    ig_media_id: '006',
    ig_user_id: 'mock_account_1',
    timestamp: '2025-08-19T13:45:00Z',
    media_type: 'CAROUSEL_ALBUM',
    caption: 'Fresh flowers from the garden 🌸 #flowers #garden',
    media_url: 'https://picsum.photos/800/800?random=6',
    thumbnail_url: 'https://picsum.photos/400/400?random=6',
    permalink: 'https://www.instagram.com/p/mock006/',
    like_count: 5,
    comments_count: 0,
    reach: 56,
    views: 121,
    shares: 0,
    saved: 0
  },
  {
    ig_media_id: '007',
    ig_user_id: 'mock_account_1',
    timestamp: '2025-08-15T08:30:00Z',
    media_type: 'CAROUSEL_ALBUM',
    caption: 'Morning workout routine 💪 #fitness #morning',
    media_url: 'https://picsum.photos/800/800?random=7',
    thumbnail_url: 'https://picsum.photos/400/400?random=7',
    permalink: 'https://www.instagram.com/p/mock007/',
    like_count: 4,
    comments_count: 0,
    reach: 25,
    views: 64,
    shares: 0,
    saved: 0
  },
  {
    ig_media_id: '008',
    ig_user_id: 'mock_account_1',
    timestamp: '2025-08-14T17:20:00Z',
    media_type: 'CAROUSEL_ALBUM',
    caption: 'Homemade pizza night 🍕 #pizza #homemade #food',
    media_url: 'https://picsum.photos/800/800?random=8',
    thumbnail_url: 'https://picsum.photos/400/400?random=8',
    permalink: 'https://www.instagram.com/p/mock008/',
    like_count: 6,
    comments_count: 0,
    reach: 33,
    views: 71,
    shares: 0,
    saved: 0
  },
  {
    ig_media_id: '009',
    ig_user_id: 'mock_account_1',
    timestamp: '2025-08-12T12:10:00Z',
    media_type: 'CAROUSEL_ALBUM',
    caption: 'Reading time with a good book 📚 #books #reading',
    media_url: 'https://picsum.photos/800/800?random=9',
    thumbnail_url: 'https://picsum.photos/400/400?random=9',
    permalink: 'https://www.instagram.com/p/mock009/',
    like_count: 5,
    comments_count: 0,
    reach: 48,
    views: 61,
    shares: 0,
    saved: 0
  },
  {
    ig_media_id: '010',
    ig_user_id: 'mock_account_1',
    timestamp: '2025-08-08T15:40:00Z',
    media_type: 'CAROUSEL_ALBUM',
    caption: 'Art museum visit 🎨 #art #museum #culture',
    media_url: 'https://picsum.photos/800/800?random=10',
    thumbnail_url: 'https://picsum.photos/400/400?random=10',
    permalink: 'https://www.instagram.com/p/mock010/',
    like_count: 5,
    comments_count: 0,
    reach: 41,
    views: 55,
    shares: 0,
    saved: 0
  },
  {
    ig_media_id: '011',
    ig_user_id: 'mock_account_1',
    timestamp: '2025-08-08T19:25:00Z',
    media_type: 'VIDEO',
    caption: 'Quick cooking tutorial - easy pasta recipe 🍝 #cooking #tutorial #video',
    media_url: 'https://picsum.photos/800/800?random=11',
    thumbnail_url: 'https://picsum.photos/400/400?random=11',
    permalink: 'https://www.instagram.com/p/mock011/',
    like_count: 5,
    comments_count: 0,
    reach: 36,
    views: 50,
    shares: 0,
    saved: 0
  },
  {
    ig_media_id: '012',
    ig_user_id: 'mock_account_1',
    timestamp: '2025-08-07T11:50:00Z',
    media_type: 'CAROUSEL_ALBUM',
    caption: 'Weekend farmer\'s market finds 🥕 #market #organic #healthy',
    media_url: 'https://picsum.photos/800/800?random=12',
    thumbnail_url: 'https://picsum.photos/400/400?random=12',
    permalink: 'https://www.instagram.com/p/mock012/',
    like_count: 7,
    comments_count: 0,
    reach: 47,
    views: 73,
    shares: 0,
    saved: 0
  },
  {
    ig_media_id: '013',
    ig_user_id: 'mock_account_1',
    timestamp: '2025-08-05T14:15:00Z',
    media_type: 'CAROUSEL_ALBUM',
    caption: 'Ocean waves and blue skies 🌊 #ocean #beach #nature',
    media_url: 'https://picsum.photos/800/800?random=13',
    thumbnail_url: 'https://picsum.photos/400/400?random=13',
    permalink: 'https://www.instagram.com/p/mock013/',
    like_count: 6,
    comments_count: 0,
    reach: 51,
    views: 74,
    shares: 0,
    saved: 0
  }
]

// Account mock data for context
export const mockAccountData = {
  id: 1,
  name: 'Mock Account',
  ig_user_id: 'mock_account_1',
  username: '@mock_lifestyle',
  profile_picture_url: 'https://picsum.photos/150/150?random=100'
}